/******************************************************************************
 * Copyright (c) David Orme and others
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    David Orme - initial API and implementation
 ******************************************************************************/
package org.eclipse.e4.enterprise.installer;

import org.eclipse.core.runtime.IStatus;

/**
 * Class InstallError.  A checked exception representing configuration problems 
 * detected during an install or update operation.
 * <p>
 * Checked exceptions are thrown either:
 * <ul>
 * <li>When something must be logged</li>
 * <li>Or when the user might need notification</li>
 * </ul>
 */
public class InstallError extends Exception {

	private static final long serialVersionUID = -229518608101965778L;
	
	/**
	 * The actual error object generated by the Eclipse runtime.
	 */
	public final IStatus status;

	public InstallError(IStatus status) {
		super(status.getMessage());
		this.status = status;
	}

	public InstallError(Throwable throwable) {
		super(throwable);
		this.status = null;
	}

	public InstallError(IStatus status, Throwable throwable) {
		super(status.getMessage(), throwable);
		this.status = status;
	}

	public InstallError(String message) {
		super(message);
		status = null;
	}

}
