var Constants = {
	ATTRIBUTE_EQUALS : "=",
	DIRECTIVE_EQUALS : ":=",
	PARAMETER_DELIMITER : ";",
	MANDATORY_DELIMITER : ",",
	SCRIPT_PATH_DELIMITER : ",",
	CLAUSE_DELIMITER : ",",
	BUNDLE_SYMBOLICNAME : "Bundle-SymbolicName",
	BUNDLE_VERSION : "Bundle-Version",
	IMPORT_PACKAGE : "Import-Package",
	EXPORT_PACKAGE : "Export-Package",
	REQUIRE_BUNDDLE : "Require-Bundle",
	BUNDLE_SCRIPT : "Bundle-Script",
	BUNDLE_SCRIPTPATH : "Bundle-ScriptPath",
	BUNDLE_ACTIVATOR : "Bundle-Activator",
	SCRIPT_PATH_DOT : ".",
	BUNDLE_SYMBOLICNAME_ATTRIBUTE : "bundle-symbolic-name",
	BUNDLE_VERSION_ATTRIBUTE : "bundle-version",
	VERSION_ATTRIBUTE : "version",
	RESOLUTION_DIRECTIVE : "resolution",
	RESOLUTION_OPTIONAL : "optional",
	RESOLUTION_MANDATORY : "mandatory",
	MANDATORY_DIRECTIVE : "mandatory",
	SINGLETON_DIRECTIVE : "singleton"
};